### ISSUE TITLE
HTML spacing

### ISSUE THREAD

**Issue by Rodrigap** [Inngravitto/tea_cozy#1]
https://github.com/Inngravitto/tea_cozy/blob/d63b90b59743d3aa63170805f806aaa1e57d3741/index.html#L2-L33

Your HTML looks really good! You used appropriate element tags for everything, and your indentation is all great. However, you have a lot of excessive spacing. Remember that you shouldn't have any blank lines between elements, and that each indentation should just be two individual spaces, not a whole tab. Here's how this little snippet should look:

```
  <html>
  <head>
    <title>Tea cozy</title>
    <link rel="stylesheet" type="text/css" href="./resources/css/style.css">
  </head>
  <body>
    <!-- Header Section -->
    <header>
      <div class="logo">
        <img src="./resources/pics/img-tea-cozy-logo.png" width="160px">
      </div>
      <nav>
        <span>
          <a href="#mission">Mission</a>
        </span>		
        <span>
          <a href="#main">Featured Tea</a>
        </span>
        <span>
          <a href="#container-locations">Locations</a>
        </span>
      </nav>
    </header>
```

**Comment by Inngravitto** [comment]
Thank you for your advice! I've already modified the file following your advice
